# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Real Space Program
tagline:             'A Kerbal Space Program adventure!'
description:         'Real space program is a community run KSP multiplayer with real roles and missions, using the Realism Overhaul and Real Solar System mods by NathanKell'
url:                 http://ksp-rsp.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Real Space Program
  url:               
  email:             

# Custom vars
version:             1.0.0
